### ISSUE TITLE
Installation issue with R 3.3.0

### ISSUE THREAD

**Issue by vatese** [tengmx/gcapc#1]
When installing I get this issue:

ERROR: this R is version 3.3.0, package 'gcapc' requires R >= 3.4
Error: Command failed (1)

It is interesting because at the moment there is no official R 3.4 release.

Cheers,

**Comment by tengmx** [comment]
@vatese Thank you for your comments. We are working on submitting this package to Bioconductor, which requires us to use the development version of R (3.4). So two solutions for installation: 1) use the developmental version of R; or 2) change the Description file manually to R>=3.3, and then install.

**Comment by vatese** [comment]
Indeed I installed correctly by changing the  R dependency version in the DESCRIPTION file. Many thanks and will notify if I find any bugs.
